[package]
name = "table-gen-terminal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "table-gen terminal renderer implementations"
readme.workspace = true
keywords = ["terminal", "library"]
categories.workspace = true
homepage.workspace = true

[lib]
name = "table_gen_terminal"

[dependencies]
bitflags.workspace = true
table-gen-core.workspace = true
