[workspace]
resolver = "3"
members = [
	"table-gen",
	"table-gen-*",
]

[workspace.package]
version = "0.8.2"
authors = ["Skylor R Schermer <skyschermer@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/solarretrace/table-fmt-rs"
description = "A formatted table generator library"
readme = "readme.md"
keywords = ["utility", "generator", "library"]
categories = ["template-engine", "value-formatting"]
homepage = "https://github.com/solarretrace/table-fmt-rs"
exclude = [
	"*.sublime-project",
	"*.sublime-workspace",
	".kateproject",
]

# Required dependencies
[workspace.dependencies]
table-gen = { version = "*", path = "./table-gen" }
table-gen-markdown = { version = "*", path = "./table-gen-markdown" }
table-gen-terminal = { version = "*", path = "./table-gen-terminal" }
bitflags = "2.13"


# The development profile, used for `cargo build`
[profile.dev]
opt-level = 0
debug = false

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = true
