[workspace]
resolver = "3"
members = [
	"table-gen",
	"table-gen-*",
]

[workspace.package]
version = "0.10.8"
authors = ["Skylor R Schermer <skyschermer@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/solarretrace/table-fmt-rs"
description = "A formatted table generator library"
readme = "readme.md"
keywords = ["utility", "generator", "library"]
categories = ["template-engine", "value-formatting"]
homepage = "https://github.com/solarretrace/table-fmt-rs"
exclude = [
	"*.sublime-project",
	"*.sublime-workspace",
	".kateproject",
]

# Required dependencies
[workspace.dependencies]
table-gen = { version = "*", path = "./table-gen" }
table-gen-markdown = { version = "*", path = "./table-gen-markdown" }
table-gen-terminal = { version = "*", path = "./table-gen-terminal" }
bitflags = "2.13"


# The development profile, used for `cargo build`
[profile.dev]
opt-level = 0
debug = false

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = true


[workspace.lints.rust]
# Forbid
non_ascii_idents = "forbid"
# Warn
absolute_paths_not_starting_with_crate = "warn"
ambiguous_negative_literals = "warn"
closure_returning_async_block = "warn"
deprecated_in_future = "warn"
deprecated_safe_2024 = "warn"
deref_into_dyn_supertrait = "warn"
edition_2024_expr_fragment_specifier = "warn"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
ffi_unwind_calls = "warn"
if_let_rescope = "warn"
impl_trait_overcaptures = "warn"
impl_trait_redundant_captures = "warn"
keyword_idents_2018 = "warn"
keyword_idents_2024 = "warn"
let_underscore_drop = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
missing_unsafe_on_extern = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
rust_2021_incompatible_closure_captures = "warn"
rust_2021_incompatible_or_patterns = "warn"
rust_2021_prefixes_incompatible_syntax = "warn"
rust_2021_prelude_collisions = "warn"
rust_2024_guarded_string_incompatible_syntax = "warn"
rust_2024_incompatible_pat = "warn"
rust_2024_prelude_collisions = "warn"
single_use_lifetimes = "warn"
tail_expr_drop_order = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unit_bindings = "warn"
unnameable_types = "warn"
unreachable_pub = "warn"
unsafe_attr_outside_unsafe = "warn"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
unused_crate_dependencies = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"
unused_results = "warn"
variant_size_differences = "warn"

[workspace.lints.clippy]
# Groups:
cargo = "warn"
nursery = "warn"
redundant_pub_crate = "allow"
pedantic = "warn"
# Restriction lints:
clone_on_ref_ptr = "warn"
create_dir = "warn"
dbg_macro = "warn"
decimal_literal_representation = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
filetype_is_file = "warn"
float_cmp_const = "warn"
lossy_float_literal = "warn"
map_err_ignore = "warn"
mem_forget = "warn"
missing_docs_in_private_items = "warn"
missing_enforced_import_renames = "warn"
mod_module_files = "warn"
multiple_inherent_impl = "warn"
print_stderr = "warn"
print_stdout = "warn"
rc_buffer = "warn"
rest_pat_in_fully_bound_structs = "warn"
string_add = "warn"
unneeded_field_pattern = "warn"
verbose_file_reads = "warn"

# Allow
# Non-improvement lints:
cast_precision_loss = "allow"
cognitive_complexity = "allow"
default_trait_access = "allow"
enum_glob_use = "allow"
match_bool = "allow"
needless_pass_by_value = "allow"
single_match_else = "allow"
unseparated_literal_suffix = "allow"
uninlined_format_args = "allow"
# Unreliable lints. May be enabled for spot checking:
inline_always = "allow"
option_if_let_else = "allow"
module_name_repetitions = "allow"
wildcard_imports = "allow"
missing_const_for_fn = "allow"
shadow_unrelated = "allow"
