[package]
name = "table-gen-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "table-gen core crate"
readme.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true

[lib]
name = "table_gen_core"

[dependencies]
bitflags = "2.13"
seq-macro = "0.3"
smallvec = "1.15"
