[package]
name = "table-gen"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "table generator API crate"
readme.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true

[lib]
name = "table_gen"

[dependencies]
bitflags.workspace = true
seq-macro = "0.3"
smallvec = "1.15"
